// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudKMSV1
@_spi(GoogleCloudInternal) public import GoogleGax

/// Provides a cross-region view of all Cloud KMS keys in a given Cloud project.
///
/// @Snippet(path: "KeyDashboardServiceQuickstart")
public final class KeyDashboardServiceClient: Clients.KeyDashboardServiceProtocol, Sendable {
  let inner: any Clients.KeyDashboardServiceStub

  /// Creates a new `KeyDashboardServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.KeyDashboardServiceStub = try Clients.KeyDashboardServiceTransport(
      options)
    inner = Clients.KeyDashboardServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.KeyDashboardServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Returns cryptographic keys managed by Cloud KMS in a given Cloud project.
  /// Note that this data is sourced from snapshots, meaning it may not
  /// completely reflect the actual state of key metadata at call time.
  ///
  /// @Snippet(path: "KeyDashboardService_ListCryptoKeys")
  public func listCryptoKeys(
    request: ListCryptoKeysRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudKMSInventoryV1.ListCryptoKeysResponse {
    try await self.inner.listCryptoKeys(request: request, options: options)
  }

  /// Returns cryptographic keys managed by Cloud KMS in a given Cloud project.
  /// Note that this data is sourced from snapshots, meaning it may not
  /// completely reflect the actual state of key metadata at call time.
  ///
  /// @Snippet(path: "KeyDashboardService_ListCryptoKeys")
  public func listCryptoKeys(
    byItem: ListCryptoKeysRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudKMSV1.CryptoKey, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudKMSInventoryV1.ListCryptoKeysResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listCryptoKeys(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }
}

extension Clients {
  /// A Swift protocol to mock `KeyDashboardServiceClient`.
  ///
  /// To mock `KeyDashboardServiceClient` change your functions to receive
  /// `some KeyDashboardServiceProtocol` or `any KeyDashboardServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol KeyDashboardServiceProtocol {
    /// See `KeyDashboardServiceClient.listCryptoKeys`.
    func listCryptoKeys(request: ListCryptoKeysRequest) async throws
      -> GoogleCloudKMSInventoryV1.ListCryptoKeysResponse

    /// See `KeyDashboardServiceClient.listCryptoKeys`.
    func listCryptoKeys(
      byItem: ListCryptoKeysRequest
    ) -> any AsyncSequence<GoogleCloudKMSV1.CryptoKey, Swift.Error>

    /// See `KeyDashboardServiceClient.listCryptoKeys`.
    func listCryptoKeys(
      parent: Swift.String,
    ) -> any AsyncSequence<GoogleCloudKMSV1.CryptoKey, Swift.Error>

    /// See `KeyDashboardServiceClient.listCryptoKeys`.
    func listCryptoKeys(
      request: ListCryptoKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSInventoryV1.ListCryptoKeysResponse

    /// See `KeyDashboardServiceClient.listCryptoKeys`.
    func listCryptoKeys(
      byItem: ListCryptoKeysRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<GoogleCloudKMSV1.CryptoKey, Swift.Error>
  }
}

// Default implementations
extension Clients.KeyDashboardServiceProtocol {
  public func listCryptoKeys(request: ListCryptoKeysRequest) async throws
    -> GoogleCloudKMSInventoryV1.ListCryptoKeysResponse
  {
    try await self.listCryptoKeys(request: request, options: .init())
  }

  public func listCryptoKeys(
    request: ListCryptoKeysRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudKMSInventoryV1.ListCryptoKeysResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listCryptoKeys(
    byItem: ListCryptoKeysRequest
  ) -> any AsyncSequence<GoogleCloudKMSV1.CryptoKey, Swift.Error> {
    self.listCryptoKeys(byItem: byItem, options: .init())
  }

  public func listCryptoKeys(
    byItem: ListCryptoKeysRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudKMSV1.CryptoKey, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudKMSInventoryV1.ListCryptoKeysResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCryptoKeys(
    parent: Swift.String,
  ) -> any AsyncSequence<GoogleCloudKMSV1.CryptoKey, Swift.Error> {
    let request = ListCryptoKeysRequest().with {
      $0.parent = parent
    }
    return self.listCryptoKeys(byItem: request)
  }
}
