// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  class KeyTrackingServiceTransport: KeyTrackingServiceStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://kmsinventory.googleapis.com",
      )
    }

    public func getProtectedResourcesSummary(
      request: GetProtectedResourcesSummaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudKMSInventoryV1.ProtectedResourcesSummary {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/protectedResourcesSummary"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.fallbackScope, prefix: "fallbackScope"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudKMSInventoryV1.ProtectedResourcesSummary.self, timeout: options.attemptTimeout
      ).get()
    }

    public func searchProtectedResources(
      request: SearchProtectedResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudKMSInventoryV1.SearchProtectedResourcesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.scope as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.scope' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/protectedResources:search"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.cryptoKey, prefix: "cryptoKey"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.resourceTypes, prefix: "resourceTypes"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: "X-Goog-Api-Client", value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudKMSInventoryV1.SearchProtectedResourcesResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }
  }
}
