// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Aggregate information about the resources protected by a Cloud KMS key in the
/// same Cloud organization/project as the key.
public struct ProtectedResourcesSummary: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The full name of the ProtectedResourcesSummary resource.
  /// Example:
  /// projects/test-project/locations/us/keyRings/test-keyring/cryptoKeys/test-key/protectedResourcesSummary
  public var name: Swift.String = Swift.String()

  /// The total number of protected resources in the same Cloud organization as
  /// the key.
  public var resourceCount: Swift.Int64 = Swift.Int64()

  /// The number of distinct Cloud projects in the same Cloud organization as the
  /// key that have resources protected by the key.
  public var projectCount: Swift.Int32 = Swift.Int32()

  /// The number of resources protected by the key grouped by resource type.
  public var resourceTypes: [Swift.String: Swift.Int64] = [:]

  /// The number of resources protected by the key grouped by Cloud product.
  public var cloudProducts: [Swift.String: Swift.Int64] = [:]

  /// The number of resources protected by the key grouped by region.
  public var locations: [Swift.String: Swift.Int64] = [:]

  /// Warning messages for the state of response
  /// [ProtectedResourcesSummary][google.cloud.kms.inventory.v1.ProtectedResourcesSummary]
  /// For example, if the organization service account is not configured,
  /// INSUFFICIENT_PERMISSIONS_PARTIAL_DATA warning will be returned.
  ///
  /// [google.cloud.kms.inventory.v1.ProtectedResourcesSummary]: <doc:ProtectedResourcesSummary>
  public var warnings: [Warning] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ProtectedResourcesSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProtectedResourcesSummary().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let resourceCount = CodingKeys(stringValue: "resourceCount")
    static let projectCount = CodingKeys(stringValue: "projectCount")
    static let resourceTypes = CodingKeys(stringValue: "resourceTypes")
    static let cloudProducts = CodingKeys(stringValue: "cloudProducts")
    static let locations = CodingKeys(stringValue: "locations")
    static let warnings = CodingKeys(stringValue: "warnings")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "resourceCount",
      "projectCount",
      "resourceTypes",
      "cloudProducts",
      "locations",
      "warnings",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .resourceCount) {
      self.resourceCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .projectCount) {
      self.projectCount = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.Int64].self, forKey: .resourceTypes)
    {
      self.resourceTypes = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.Int64].self, forKey: .cloudProducts)
    {
      self.cloudProducts = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.Int64].self, forKey: .locations)
    {
      self.locations = value
    }
    if let value = try container.decodeIfPresent([Warning].self, forKey: .warnings) {
      self.warnings = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.resourceCount, forKey: .resourceCount)
    try container.encode(self.projectCount, forKey: .projectCount)
    try container.encode(self.resourceTypes, forKey: .resourceTypes)
    try container.encode(self.cloudProducts, forKey: .cloudProducts)
    try container.encode(self.locations, forKey: .locations)
    try container.encode(self.warnings, forKey: .warnings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.inventory.v1.ProtectedResourcesSummary"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
