// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Metadata about a resource protected by a Cloud KMS key.
public struct ProtectedResource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The full resource name of the resource.
  /// Example:
  /// `//compute.googleapis.com/projects/my_project_123/zones/zone1/instances/instance1`.
  public var name: Swift.String = Swift.String()

  /// Format: `projects/{PROJECT_NUMBER}`.
  public var project: Swift.String = Swift.String()

  /// The ID of the project that owns the resource.
  public var projectId: Swift.String = Swift.String()

  /// The Cloud product that owns the resource.
  /// Example: `compute`
  public var cloudProduct: Swift.String = Swift.String()

  /// Example: `compute.googleapis.com/Disk`
  public var resourceType: Swift.String = Swift.String()

  /// Location can be `global`, regional like `us-east1`, or zonal like
  /// `us-west1-b`.
  public var location: Swift.String = Swift.String()

  /// A key-value pair of the resource's labels (v1) to their values.
  public var labels: [Swift.String: Swift.String] = [:]

  /// The name of the Cloud KMS
  /// [CryptoKeyVersion](https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys.cryptoKeyVersions?hl=en)
  /// used to protect this resource via CMEK. This field is empty if the
  /// Google Cloud product owning the resource does not provide key version data
  /// to Asset Inventory. If there are multiple key versions protecting the
  /// resource, then this is same value as the first element of
  /// crypto_key_versions.
  public var cryptoKeyVersion: Swift.String = Swift.String()

  /// The names of the Cloud KMS
  /// [CryptoKeyVersion](https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys.cryptoKeyVersions?hl=en)
  /// used to protect this resource via CMEK. This field is empty if the
  /// Google Cloud product owning the resource does not provide key versions data
  /// to Asset Inventory. The first element of this field is stored in
  /// crypto_key_version.
  public var cryptoKeyVersions: [Swift.String] = []

  /// Output only. The time at which this resource was created. The granularity
  /// is in seconds. Timestamp.nanos will always be 0.
  public var createTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ProtectedResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProtectedResource().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let project = CodingKeys(stringValue: "project")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let cloudProduct = CodingKeys(stringValue: "cloudProduct")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let location = CodingKeys(stringValue: "location")
    static let labels = CodingKeys(stringValue: "labels")
    static let cryptoKeyVersion = CodingKeys(stringValue: "cryptoKeyVersion")
    static let cryptoKeyVersions = CodingKeys(stringValue: "cryptoKeyVersions")
    static let createTime = CodingKeys(stringValue: "createTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "project",
      "projectId",
      "cloudProduct",
      "resourceType",
      "location",
      "labels",
      "cryptoKeyVersion",
      "cryptoKeyVersions",
      "createTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
      self.project = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloudProduct) {
      self.cloudProduct = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cryptoKeyVersion) {
      self.cryptoKeyVersion = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .cryptoKeyVersions) {
      self.cryptoKeyVersions = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.project, forKey: .project)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.cloudProduct, forKey: .cloudProduct)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.cryptoKeyVersion, forKey: .cryptoKeyVersion)
    try container.encode(self.cryptoKeyVersions, forKey: .cryptoKeyVersions)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.inventory.v1.ProtectedResource"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
